[package]
name = "bima_v1_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
risc0-zkp = { git = "https://github.com/risc0/risc0.git" } 
risc0-zkvm = { git = "https://github.com/risc0/risc0.git" }
ink_lang = { version = "3.0", default-features = false }
ink_env = { version = "5.0.0", default-features = false }
num-bigint = "0.4.0"
num-traits = "0.2.14"
ink_storage = "5.0.0"  # Removed features = ["no_std"]
ink_engine = "5.0.0"
secp256k1 = "0.29.1"


[features]
std = ["ink_lang/std", "ink_storage/std"]

